USE [master]
GO

/****** Object:  Database [issues_dev]    Script Date: 26/07/2013 12:27:52 ******/
CREATE DATABASE [issues_dev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'issues_dev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\issues_dev2.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'issues_dev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\issues_dev_log2.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [issues_dev] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [issues_dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [issues_dev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [issues_dev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [issues_dev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [issues_dev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [issues_dev] SET ARITHABORT OFF 
GO

ALTER DATABASE [issues_dev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [issues_dev] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [issues_dev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [issues_dev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [issues_dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [issues_dev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [issues_dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [issues_dev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [issues_dev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [issues_dev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [issues_dev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [issues_dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [issues_dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [issues_dev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [issues_dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [issues_dev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [issues_dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [issues_dev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [issues_dev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [issues_dev] SET  MULTI_USER 
GO

ALTER DATABASE [issues_dev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [issues_dev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [issues_dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [issues_dev] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [issues_dev] SET  READ_WRITE 
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[note](
	[issue] [int] NULL,
	[created] [datetime] NULL,
	[createdby] [nvarchar](128) NULL,
	[note] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[note]  WITH CHECK ADD  CONSTRAINT [FK_note_issue] FOREIGN KEY([issue])
REFERENCES [dbo].[issue] ([id])
GO

ALTER TABLE [dbo].[note] CHECK CONSTRAINT [FK_note_issue]
GO


CREATE TABLE [dbo].[issue](
	[id] [int] NOT NULL,
	[title] [varchar](255) NOT NULL,
	[description] [varchar](max) NOT NULL,
	[application] [varchar](50) NOT NULL,
	[reproduce] [nvarchar](max) NOT NULL,
	[impact] [varchar](50) NOT NULL,
	[internal] [tinyint] NOT NULL,
	[duplicate_of] [int] NULL,
 CONSTRAINT [PK_issue] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


