package com.trabajo.engine.annotation;

public enum ApplicationPoint {
	BEFORE_INSTANCE_START, 
	AFTER_INSTANCE_START,
	BEFORE_INSTANCE_END, 
	AFTER_INSTANCE_END,
	BEFORE_TASK_CREATE, 
	AFTER_TASK_CREATE, 
	BEFORE_TASK_VIEW, 
	AFTER_TASK_VIEW, 
	BEFORE_TASK_DATA, 
	AFTER_TASK_DATA, 
	BEFORE_TASK_DISPOSE, 
	AFTER_TASK_DISPOSE, 
	BEFORE_TASK_TIMEOUT, 
	AFTER_TASK_TIMEOUT 
}
